version: '3.9'

services:
  prefect:
    build: .
    container_name: prefect
    networks:
      - app-network
    command: ["uv","run","prefect","server","start"]

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: python-app
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - app-network
    command: ["uv", "run", "./extract.py"]

volumes:
  mongo-data:

networks:
  app-network:
